name = "Aggressively Mediocre"
license = "MIT"
licenselink = "https://github.com/katesowles/aggressively-mediocre-theme/blob/master/LICENSE"
description = "Minimal Hugo theme."
homepage = "https://github.com/katesowles/aggressively-mediocre-theme/"
tags = ["blog", "minimal"]
features = ["blog"]
min_version = "0.20"

[author]
  name = "Kate Sowles"
  homepage = "https://github.com/katesowles"
