name: Lighthouse (Mobile)
on:
  pull_request:
    branches:
      - release
      - staging
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: Wait for Netlify
        uses: JakePartusch/wait-for-netlify-action@v1.2
        id: waitFor200
        with:
          site_name: angry-kirby-8b4540

      - name: Audit mobile preview
        run: |
          sudo npm install -g @lhci/cli@0.4.x
          lhci autorun healthcheck --config=./.github/lighthouse/lighthouserc.deploy.js
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
